[font]
normal.family = "MesloLGL Nerd Font"
normal.style = "Bold"
italic.style = "Bold Italic"
size = 16.0

[window]
dimensions.columns = 300 #Full width
dimensions.lines = 100 #Full height
padding.x = 30
padding.y = 30
dynamic_padding = true
decorations = "Transparent"
option_as_alt = "Both"

[general]
import = ["~/.config/alacritty/themes/chalkboard/chalkboard.toml"]
