#!/usr/bin/env bash

source "${CONFIG_DIR}/themes/catppuccin-macchiato.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top \
                 height=30 \
                 color="${_COLOUR_BACKGROUND_MAIN_TRANS}" \
                 blur_radius=32 

default=(
  padding_left=0
  padding_right=0
  icon.font="MesloLGL Nerd Font:Bold:17.0"
  label.font="Ubuntu Nerd Font:Bold:15.0"
  icon.color="${_SSDF_CM_SUBTEXT_1}"
  label.color="${_SSDF_CM_SUBTEXT_1}"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=0
  label.padding_right=14
)
sketchybar --default "${default[@]}"

# -- Left --
source "${CONFIG_DIR}/items/decoration-icon.sh"
source "${CONFIG_DIR}/items/front_app.sh"
source "${CONFIG_DIR}/items/aerospace.sh"

# -- Center --
source "${CONFIG_DIR}/items/date.sh"

# -- Right --
source "${CONFIG_DIR}/items/time.sh"

sketchybar --update
