#!/bin/bash

options=(
        style=round
        width=5.0
        #order=above
        hidpi=on
        active_color=0xFF5E5E5E
        inactive_color=0xFFCDCDCD
)

blacklist="java,Minecraft"

borders "${options[@]}"
