#!/bin/zsh

loading_icon() {
  local pid=$1
  local delay=0.1
  local spinstr='|/-\'
  echo -n "Reloading config... "
  while kill -0 $pid 2>/dev/null; do
    printf " [%c]  " "$spinstr"
    spinstr=${spinstr#?}${spinstr%${spinstr#?}}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done
  echo ""
}

reload_config() {
  (
    sleep 0.5
    aerospace reload-config > /dev/null 2>&1 &&
    sketchybar --reload > /dev/null 2>&1 &&
    brew services restart borders > /dev/null 2>&1
  ) &
  local pid=$!
  loading_icon $pid
  wait $pid
  [[ $? -eq 0 ]] && echo "Config reloaded successfully!" || echo "Config reload has failed."
}

switch_config() {
  local branch=$1
  cd ~/.config || exit 1
  git switch "$branch" > /dev/null 2>&1
  ./scripts/config reload
}

case "$1" in
  reload)
    reload_config
    ;;
  query)
    cd ~/.config
    echo -n 'Current config: ' && git rev-parse --abbrev-ref HEAD
    ;;
  switch)
    case "$2" in
      round)
        switch_config main
        ;;
      square)
        switch_config square-borders
        ;;
      *)
        echo "Unknown switch target: $2"
        ;;
    esac
    ;;
  *)
    echo 'Config commands:'
    echo '- config reload'
    echo '- config query'
    echo '- config switch round|square'
    ;;
esac

