#!/bin/zsh

alias "pkg"="brew"

if [[ "$1" == "clean" ]]; then
    echo "\033[34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
    echo "\033[34m┃\033[0mPerforming deep clean (update, upgrade, cleanup).\033[34m┃"
    
    # Run brew commands and capture exit status
    brew update && brew upgrade && brew cleanup --prune=all
    BREW_STATUS=$?  # Capture exit status of the last command
    
    echo "\033[34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"

    if [ $BREW_STATUS -eq 0 ]; then
        # Success: Show green "PKG cleanup performed successfully."
        echo "\033[32m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
        echo "┃       PKG cleanup performed successfully.       ┃"
    else
        # Failure: Show red "PKG cleanup failed."
        echo "\033[31m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
        echo "┃               PKG cleanup failed.               ┃"
    fi
    echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
fi
