#!/bin/zsh

alias "pkg"="brew"

if [[ "$1" == "clean" ]]; then
    echo "\033[34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
    echo "\033[34m┃\033[0mPerforming deep clean (update, upgrade, cleanup).\033[34m┃"
    
    brew update && brew upgrade && brew cleanup --prune=all
    BREW_STATUS=$?
    
    echo "\033[34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"

    if [ $BREW_STATUS -eq 0 ]; then
        echo "\033[32m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
        echo "┃       PKG cleanup performed successfully.       ┃"
    else
        echo "\033[31m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
        echo "┃               PKG cleanup failed.               ┃"
    fi
    echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
fi
